### ISSUE TITLE
编译时报错，尝试把fis3-parser-vue 换成fis-parser-vue 就正常了

### ISSUE THREAD

**Issue by VenyXiong** [laomu1988/fis3-vue-demo#2]
[ERROR] parser.vue: content.trim is not a function [/Users/magic/Downloads/fis3-vue-demo-master/weight/app.vue]
尝试把fis3-parser-vue里的用fis3编译的一段注释掉就好了
'use strict';

var compiler = require('vueify-sync').compiler;

module.exports = function (content, file, conf) {
  var result = '';
  // 用 HTML 相关语言能力处理一遍
  // if (fis.compile.partial && file.ext === '.vue') {
  //   try {
  //       content = fis.compile.partial(content, file, {
  //       ext: '.html',
  //       isHtmlLike: true
  //     });
  //   } catch(e) {
  //     console.log(e);
  //   }
  // }
  try {
    result = compiler.compileSync(content.toString('utf8'), file.realpath);
  } catch (e) {
    console.log(e.stack);
  }
  return result;
};

**Comment by laomu1024** [comment]
项目改为使用fis3-parser-vue-component 进行打包， 支持范围更广
